cernopendata/modules/pages/views.py
# -*- coding: utf-8 -*-
#
# This file is part of CERN Open Data Portal.
# Copyright (C) 2017 CERN.
#
# CERN Open Data Portal is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# CERN Open Data Portal is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CERN Open Data Portal; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""Pages for CERN Open Data Portal."""

from __future__ import absolute_import, print_function

import json

import pkg_resources
from flask import Blueprint, abort, current_app, escape, jsonify, redirect, \
    render_template, request, url_for
from flask_babelex import lazy_gettext as _
from flask_breadcrumbs import default_breadcrumb_root, register_breadcrumb
from flask_menu import register_menu
from jinja2.exceptions import TemplateNotFound
from speaklater import make_lazy_string

from .utils import FeaturedArticlesSearch

blueprint = Blueprint(
    'cernopendata_pages',
    __name__,
    template_folder='templates',
    static_folder='static',
)

default_breadcrumb_root(blueprint, '.')


@blueprint.errorhandler(TemplateNotFound)
def template_not_found(err):
    """Log missing template."""
    current_app.logger.exception('Please check missing template.')
    abort(404)
    # return 'Template not found!', 404


def lazy_title(text, *args):
    """Make tranlated string with escaped values from request view args."""
    return _(text, **{key: make_lazy_string(
        lambda: escape(request.view_args.get(key, ''))
    ) for key in args})


@blueprint.route('/')
# @register_breadcrumb(blueprint, '.', _('Home'))
# @register_breadcrumb(blueprint, '.education', _('Education'),
#                      endpoint_arguments_constructor=lambda: {
#                          '_anchor': 'education'})
# @register_breadcrumb(blueprint, '.research', _('Research'),
#                      endpoint_arguments_constructor=lambda: {
#                          '_anchor': 'education'})
def index():
    """Home Page."""
    results = []
    try:
        results = FeaturedArticlesSearch().sort(
            'featured')[:6].execute().hits.hits
    except:
        pass
    return render_template('cernopendata_pages/front/index.html',
                           featured_articles=results)


@blueprint.route('/md/debug', methods=['HEAD', 'GET'])
def md_debug():
    """Test Markdown rendering of a page.

    Route for quicker previewing markdown during development.
    During edit replace contents of `cernopendata/static/test_data/debug.md`
    and just refresh the view.
    I.e. there is no need to re-populate db every time a change is made.

    If DEBUG is not set this will redirect to homepage.

    Command `cernopendata collect -v` has to be run everytime
    there is a change in static resources.

    """
    if current_app.config.get('DEBUG'):
        f = open('cernopendata/static/test_data/debug.md', 'r')
        # return render_template_string(
        #     u"{{ text|markdown }}", text=f.read().decode("utf-8"))
        return render_template('cernopendata_pages/md_template.html',
                               content=f.read().decode("utf-8"))
    else:
        return redirect('/')


@blueprint.route('/visualise/events')
# @register_breadcrumb(blueprint, '.visualise_events', _('Visualise Events'))
def visualise_events_landing():
    """Display landing page."""
    try:
        return render_template(
            'cernopendata_pages/visualise_events.html')
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/visualise/events/<string:experiment>')
@blueprint.route('/visualise/events/<string:experiment>/<int:eventid>')
# @register_breadcrumb(blueprint, '.visualise_events', _('Visualise Events'))
def visualise_events(experiment='cms', eventid=None):
    """Display visualisations."""
    # if experiment == 'opera':
    #     abort(404)
    try:
        return render_template(
            'cernopendata_pages/visualise_events_{}.html'.format(
                experiment),
            eventid=eventid,
            experiment=experiment,
        )
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/visualise/histograms')
@blueprint.route('/visualise/histograms/<string:experiment>')
# @register_breadcrumb(blueprint, '.visualise_histograms',
#                      _('Visualise Histograms'))
def visualise_histograms(experiment='cms'):
    """Display histograms."""
    try:
        return render_template(
            'cernopendata_pages/visualise_histograms.html',
            experiment=experiment,
        )
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/about')
def about():
    """Render view for general about page."""
    return redirect('/docs/about')


@blueprint.route('/about/<exp>')
def about_exp(exp):
    """Render about <experiment> pages."""
    return redirect('/docs/about-{}'.format(exp))


@blueprint.route('/about/cms-pileup-simulation')
def cms_pileup_simulation():
    """Render cms pileup simulation template."""
    return redirect('/docs/cms-guide-pileup-simulation')


@blueprint.route('/about/cms-simulated-dataset-names')
def about_cms_dataset_names():
    """Render about CMS simulated dataset names template."""
    return redirect('/docs/cms-simulated-dataset-names')


@blueprint.route('/getting-started/<exp>')
def getting_started_redirect(exp):
    """Redirects to associated experiment."""
    return redirect('/docs/%s-getting-started' % exp,
                    code=302)


@blueprint.route('/vm/<exp>/<year>')
def vm_redirect(exp, year):
    """Redirects to associated experiment."""
    if year:
        return redirect(
            '/docs/%s-virtual-machine-%s' % (exp, year),
            code=302)
    return redirect('/docs/%s-virtual-machine' % exp,
                    code=302)


@blueprint.route('/vm/cms/validation/report')
def validation_report_redirect(exp):
    """Redirects to CMS VM validation document."""
    return redirect('/docs/cms-vm-validation-2010')


@blueprint.route('/cms-physics-objects/')
@blueprint.route('/cms-physics-objects/<year>')
@blueprint.route('/about/cms-physics-objects/')
@blueprint.route('/about/cms-physics-objects/<year>')
def cms_physics_objects_redirect(year='2011'):
    """Redirects to CMS physics objects page of given year.

    If no year is given, redirects to latest available
    physics objects page (the default parameter).
    """
    return redirect('/docs/cms-physics-objects-{}'.format(year), code=302)


@blueprint.route('/terms-of-use')
def terms():
    """Render terms of use."""
    return redirect('docs/terms-of-use')


@blueprint.route('/privacy-policy')
def privacy():
    """Render privacy policy."""
    return redirect('/docs/privacy-policy')


@blueprint.route('/glossary')
def glossary():
    """Display glossary terms."""
    return redirect('/search?type=Glossary&sort=title')


@blueprint.route('/glossary/json')
def glossary_json():
    """Fetch glossary json."""
    filepath = pkg_resources.resource_filename(
        'cernopendata.modules.fixtures', 'data/terms/terms.json')
    with open(filepath, 'r') as f:
        glossary = json.load(f)
    return jsonify(glossary)


@blueprint.route('/collection/<string:collection>')
@blueprint.route('/<any("getting-started","vm","news",'
                 '"datasets","documentation","software"):page>')
@blueprint.route('/<any("getting-started","vm"):page>'
                 '/<any("cms","lhcb","opera","alice","atlas"):experiment>')
def faceted_search(page=None, experiment=None, collection=None):
    """Faceted search view.

    To add a new page:
        add url to blueprint.route
        add mapping, which (filter,val,search_endpoint)
            should be used to filter records

    """
    facets = [x for x in locals().values() if x]
    filters = {}

    filter_map = {
        'documentation': ('type', 'Documentation'),
        'software': ('type', 'Software'),
        'datasets': ('type', 'Dataset'),
        'getting-started': ('tags', 'Getting Started'),
        'news': ('type', 'News'),
        'vm': ('tags', 'VM'),
        'cms': ('experiment', 'CMS'),
        'alice': ('experiment', 'ALICE'),
        'atlas': ('experiment', 'ATLAS'),
        'lhcb': ('experiment', 'LHCb'),
        'opera': ('experiment', 'OPERA'),
        'data-policies': ('collections', 'Data-Policies'),
        'alice-derived-datasets': ('collections',
                                   'ALICE-Derived-Datasets'),
        'alice-reconstructed-data': ('collections',
                                     'ALICE-Reconstructed-Data'),
        'alice-learning-resources': ('collections',
                                     'ALICE-Learning-Resources'),
        'alice-tools': ('collections', 'ALICE-Tools'),
        'atlas-derived-datasets': ('collections',
                                   'ATLAS-Derived-Datasets'),
        'atlas-higgs-challenge-2014': ('collections',
                                       'ATLAS-Higgs-Challenge-2014'),
        'atlas-simulated-datasets': ('collections',
                                     'ATLAS-Simulated-Datasets'),
        'atlas-learning-resources': ('collections',
                                     'ATLAS-Learning-Resources'),
        'atlas-tools': ('collections', 'ATLAS-Tools'),
        'author-lists': ('collections', 'Author-Lists'),

cernopendata/templates/cernopendata_pages/front/index.html
{%- extends config.BASE_TEMPLATE %}


{%- block css %}
    {{ super() }}
    {% assets "invenio_search_ui_search_css" %}<link href="{{ ASSET_URL }}" rel="stylesheet">{% endassets %}
{%- endblock css %}

{%- block page_header %}
{% include 'cernopendata_theme/header_index.html' %}
{%- endblock page_header %}
{%- block page_body %}
        {% include 'cernopendata_pages/front/main.html' %}
        {% include 'cernopendata_pages/front/lva.html' %}
        {% include 'cernopendata_pages/front/news.html' %}
{%- endblock %}

{%- block javascript %}
    {{ super() }}
{%- endblock javascript %}

cernopendata/templates/cernopendata_pages/front/lva.html
<div class="homepage-section section lva justify-content-center" id="lva" data-anchor="lva">
    <div class="container lva-container">
        <div class="lva-item-container justify-content-center align-items-center col">
            <div class="lva-item h-100">
                <header class="container-fluid">
                    <h3 class="row justify-content-center">Learn</h3>
    <!--                 <div class="row image justify-content-center">
                        <img src="{{url_for('static', filename='assets/img/learn.svg')}}" alt="">
                    </div> -->
                    <div class="row justify-content-center">
                        <div class="text">Discover the world of open data from particle physics</div>
                    </div>
                </header>

                <div class="body">
                    <ul>
                        <li class="justify-content-center row">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='welcome')}}">Welcome to our updated portal</a>
                        </li>
                        <li class="justify-content-center row">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='cms-guide-for-education')}}">CMS Guide to education use of CMS Open Data</a>
                        </li>
                        <li class="justify-content-center row">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='cms-summer-student-report-2017')}}">Improving educational content with high school teachers: A field report from our summer students</a>
                        </li>
                        <li class="justify-content-center">
                            <a href="{{url_for('cernopendata_pages.glossary')}}">Glossary</a>
                        </li>
                    </ul>
                </div>

                <div class="more justify-content-center"><a href="/search?type=Documentation">more</a></div>
            </div>
        </div>
        <div id="visualize" class="lva-item-container justify-content-center align-items-center col">
            <div class="lva-item h-100">
                <header class="container-fluid">
                    <h3 class="row justify-content-center">Visualise</h3>
                    <!-- <div class="image row justify-content-center">
                        <img  src="{{url_for('static', filename='assets/img/visualize.svg')}}" alt="">
                    </div> -->
                    <div class="row justify-content-center">
                        <div class="text">Explore detector events and run basic histogramming</div>
                    </div>
                </header>

                <div class="body">
                    <ul>
                        <li class="justify-content-center">
                            <a href="{{url_for('cernopendata_pages.visualise_events', experiment='cms')}}">CMS Event Display</a>
                        </li>
                        <li class="justify-content-center">
                            <a href="{{url_for('cernopendata_pages.visualise_events', experiment='opera')}}">OPERA Event Display</a>
                        </li>
                        <li class="justify-content-center">
                            <a href="{{url_for('cernopendata_pages.visualise_histograms')}}">CMS Histograms</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="lva-item-container justify-content-center align-items-center col">
            <div class="lva-item h-100">
                <header class="container-fluid">
                    <h3 class="row justify-content-center">Analyse</h3>
                    <!-- <div class="image row justify-content-center">
                        <img src="{{url_for('static', filename='assets/img/model.svg')}}" alt="">
                    </div> -->
                    <div class="row justify-content-center">
                        <div class="text">Run your own physics analyses, start virtual machines</div>
                    </div>
                </header>

                <div class="body">
                    <ul>
                        <li class="justify-content-center row">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='cms-guide-for-research')}}">CMS Guide to research use of CMS Open Data</a>
                        </li>
                        <li class="justify-content-center">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='atlas-higgs-machine-learning-challenge')}}">ATLAS Higgs Machine Learning Challenge</a>
                        </li>
                        <li class="justify-content-center row">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='lhcb-getting-started')}}">Getting Started with LHCb Open Data</a>
                        </li>
                        <li class="justify-content-center row">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='alice-getting-started')}}">Getting Started with ALICE Open Data</a>
                        </li>
                    </ul>
                </div>
                <div class="more justify-content-center"><a href="/research">more</a></div>
            </div>
        </div>
    </div>
    <div class="cod-scroll row justify-content-center align-self-end">
        <div class="icon justify-content-center align-items-center">
            <a href="#news">
                <img src="{{url_for('static', filename='assets/img/mouse-scrolling.png')}}" alt="">
                <span>News</span>
                <img src="{{url_for('static', filename='assets/img/mouse-scrolling.png')}}" alt="">
            </a>
        </div>
    </div>
</div>

cernopendata/templates/cernopendata_pages/front/main.html
<div class="homepage-section main section align-items-center" data-anchor="main">


        <div class="main-inner container container-main">
            <div class="cod-banner row">
                <h2>
                    <span>Explore more than <span><strong>1 petabyte</strong></span> <br>
                    <span class="scnd-line">of open data from particle physics!</span></span>
                </h2>
            </div>

            <div class="cod-search row">
                <form class="search-form container" action="{{config.THEME_SEARCH_ENDPOINT}}" role="search">
                    <input autofocus type="text" class="form-control search" name="q" placeholder="{{_('Start typing...')}}">
                    <div class="">
                        <button type="submit" class="">Search</button>
                        <div id="cod-home-image">
                            <img src="{{url_for('static', filename='assets/img/header-image.svg')}}" alt="">
                        </div>
                    </div>
                </form>
                <div class="search-examples row justify-content-center">
                    <span class="example-title">search examples:</span>
                    <a href="/search?subtype=Collision&type=Dataset">collision datasets</a>,
                    <a href="/search?keywords=education">keywords:education</a>,
                    <a href="/search?collision_energy=7TeV">energy:7TeV</a>
                </div>
            </div>

            <div class="cod-collections row justify-content-around">
                <div class="collections-col justify-content-center">
                    <header><span>Explore</span></header>
                    <ul>
                        <li><a href="/search?type=Dataset">datasets</a></li>
                        <li><a href="/search?type=Software">software</a></li>
                        <li><a href="/search?type=Environment">environments</a></li>
                        <li><a href="/search?type=Documentation">documentation</a></li>
                    </ul>
                </div>
                <div class="collections-col justify-content-center">
                    <header><span>Focus on</span></header>
                    <ul>
                        <li><a href="/search?experiment=ATLAS">ATLAS</a></li>
                        <li><a href="/search?experiment=ALICE">ALICE</a></li>
                        <li><a href="/search?experiment=CMS">CMS</a></li>
                        <li><a href="/search?experiment=LHCb">LHCb</a></li>
                        <li><a href="/search?experiment=OPERA">OPERA</a></li>
                    </ul>
                </div>
            </div>
            <div class="cod-scroll row justify-content-center align-self-end">
                <div class="icon justify-content-center align-items-center">
                    <a href="#lva">
                        <img src="{{url_for('static', filename='assets/img/mouse-scrolling.png')}}" alt="">
                        <span>Get started</span>
                        <img src="{{url_for('static', filename='assets/img/mouse-scrolling.png')}}" alt="">
                    </a>
                </div>
            </div>
        </div>
</div>

cernopendata/templates/cernopendata_pages/front/news.html
<div class="homepage-section news section align-items-center" id="news" data-anchor="news">
    <div class="container-fluid align-items-center">
        <div class="news-header">
            <h3 class="">News & Updates</h3>
        </div>
        <div class="row justify-content-space-between">
            {% for article in featured_articles %}
            {% set article = article._source %}
            <div class="news-item align-content-stretch col-sm-6 col-md-4">
                <div class="news-card container-fluid">
                    <div class="card-body">
                        <p class="row date-author-small">
                            {{ article.created or '-' }} by
                            {{ article.author or 'Open Data Portal team'}}
                        </p>
                        <div class="row">
                            <h4>
                                <a href="/docs/{{article.control_number}}">{{article.title}}</a>
                            </h4>
                        </div>
                        <div class="tags-box row align-self-end">
                            <a href="/search?type={{article.type.primary}}" class="badge  badge-success custom-badge-success">
                                {{article.type.primary }}
                            </a>
                            {% if article.type.secondary %}
                                {% for subtype in article.type.secondary %}
                                    <a href="/search?subtype={{subtype}}" class="badge  badge-info">{{ subtype }}</a>
                                {% endfor %}
                            {% endif %}
                            {% for tag in article.tags %}
                                <a href="/search?tags={{tag}}" class="badge badge-secondary">{{ tag }}</a>
                            {% endfor %}
                            {% if article.experiment %}
                            <a href="/search?experiment={{article.experiment}}" class="badge badge-warning custom-badge-warning">
                                {{ article.experiment }}
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="more-container justify-content-end">
            <div class="more justify-content-center"><a href="{{url_for('invenio_search_ui.search', type = 'News') }}">more</a></div>
        </div>
    </div>
</div>