cernopendata/modules/pages/views.py
# -*- coding: utf-8 -*-
#
# This file is part of CERN Open Data Portal.
# Copyright (C) 2017 CERN.
#
# CERN Open Data Portal is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# CERN Open Data Portal is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CERN Open Data Portal; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""Pages for CERN Open Data Portal."""

from __future__ import absolute_import, print_function

import json

import pkg_resources
from flask import Blueprint, abort, current_app, escape, jsonify, redirect, \
    render_template, request, url_for
from flask_babelex import lazy_gettext as _
from flask_breadcrumbs import default_breadcrumb_root, register_breadcrumb
from flask_menu import register_menu
from jinja2.exceptions import TemplateNotFound
from speaklater import make_lazy_string

from .utils import FeaturedArticlesSearch

blueprint = Blueprint(
    'cernopendata_pages',
    __name__,
    template_folder='templates',
    static_folder='static',
)

default_breadcrumb_root(blueprint, '.')


@blueprint.errorhandler(TemplateNotFound)
def template_not_found(err):
    """Log missing template."""
    current_app.logger.exception('Please check missing template.')
    abort(404)
    # return 'Template not found!', 404


def lazy_title(text, *args):
    """Make tranlated string with escaped values from request view args."""
    return _(text, **{key: make_lazy_string(
        lambda: escape(request.view_args.get(key, ''))
    ) for key in args})


@blueprint.route('/')
# @register_breadcrumb(blueprint, '.', _('Home'))
# @register_breadcrumb(blueprint, '.education', _('Education'),
#                      endpoint_arguments_constructor=lambda: {
#                          '_anchor': 'education'})
# @register_breadcrumb(blueprint, '.research', _('Research'),
#                      endpoint_arguments_constructor=lambda: {
#                          '_anchor': 'education'})
def index():
    """Home Page."""
    results = []
    try:
        results = FeaturedArticlesSearch().sort(
            'featured')[:6].execute().hits.hits
    except:
        pass
    return render_template('cernopendata_pages/front/index.html',
                           featured_articles=results)


@blueprint.route('/md/debug', methods=['HEAD', 'GET'])
def md_debug():
    """Test Markdown rendering of a page.

    Route for quicker previewing markdown during development.
    During edit replace contents of `cernopendata/static/test_data/debug.md`
    and just refresh the view.
    I.e. there is no need to re-populate db every time a change is made.

    If DEBUG is not set this will redirect to homepage.

    Command `cernopendata collect -v` has to be run everytime
    there is a change in static resources.

    """
    if current_app.config.get('DEBUG'):
        f = open('cernopendata/static/test_data/debug.md', 'r')
        # return render_template_string(
        #     u"{{ text|markdown }}", text=f.read().decode("utf-8"))
        return render_template('cernopendata_pages/md_template.html',
                               content=f.read().decode("utf-8"))
    else:
        return redirect('/')


@blueprint.route('/visualise/events')
# @register_breadcrumb(blueprint, '.visualise_events', _('Visualise Events'))
def visualise_events_landing():
    """Display landing page."""
    try:
        return render_template(
            'cernopendata_pages/visualise_events.html')
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/visualise/events/<string:experiment>')
@blueprint.route('/visualise/events/<string:experiment>/<int:eventid>')
# @register_breadcrumb(blueprint, '.visualise_events', _('Visualise Events'))
def visualise_events(experiment='cms', eventid=None):
    """Display visualisations."""
    # if experiment == 'opera':
    #     abort(404)
    try:
        return render_template(
            'cernopendata_pages/visualise_events_{}.html'.format(
                experiment),
            eventid=eventid,
            experiment=experiment,
        )
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/visualise/histograms')
@blueprint.route('/visualise/histograms/<string:experiment>')
# @register_breadcrumb(blueprint, '.visualise_histograms',
#                      _('Visualise Histograms'))
def visualise_histograms(experiment='cms'):
    """Display histograms."""
    try:
        return render_template(
            'cernopendata_pages/visualise_histograms.html',
            experiment=experiment,
        )
    except TemplateNotFound:
        return abort(404)


@blueprint.route('/about')
def about():
    """Render view for general about page."""
    return redirect('/docs/about')


@blueprint.route('/about/<exp>')
def about_exp(exp):
    """Render about <experiment> pages."""
    return redirect('/docs/about-{}'.format(exp))


@blueprint.route('/about/cms-pileup-simulation')
def cms_pileup_simulation():
    """Render cms pileup simulation template."""
    return redirect('/docs/cms-guide-pileup-simulation')


@blueprint.route('/about/cms-simulated-dataset-names')
def about_cms_dataset_names():
    """Render about CMS simulated dataset names template."""
    return redirect('/docs/cms-simulated-dataset-names')


@blueprint.route('/getting-started/<exp>')
def getting_started_redirect(exp):
    """Redirects to associated experiment."""
    return redirect('/docs/%s-getting-started' % exp,
                    code=302)


@blueprint.route('/vm/<exp>/<year>')
def vm_redirect(exp, year):
    """Redirects to associated experiment."""
    if year:
        return redirect(
            '/docs/%s-virtual-machine-%s' % (exp, year),
            code=302)
    return redirect('/docs/%s-virtual-machine' % exp,
                    code=302)


@blueprint.route('/vm/cms/validation/report')
def validation_report_redirect(exp):
    """Redirects to CMS VM validation document."""
    return redirect('/docs/cms-vm-validation-2010')


@blueprint.route('/cms-physics-objects/')
@blueprint.route('/cms-physics-objects/<year>')
@blueprint.route('/about/cms-physics-objects/')
@blueprint.route('/about/cms-physics-objects/<year>')
def cms_physics_objects_redirect(year='2011'):
    """Redirects to CMS physics objects page of given year.

    If no year is given, redirects to latest available
    physics objects page (the default parameter).
    """
    return redirect('/docs/cms-physics-objects-{}'.format(year), code=302)


@blueprint.route('/terms-of-use')
def terms():
    """Render terms of use."""
    return redirect('docs/terms-of-use')


@blueprint.route('/privacy-policy')
def privacy():
    """Render privacy policy."""
    return redirect('/docs/privacy-policy')


@blueprint.route('/glossary')
def glossary():
    """Display glossary terms."""
    return redirect('/search?type=Glossary&sort=title')


@blueprint.route('/glossary/json')
def glossary_json():
    """Fetch glossary json."""
    filepath = pkg_resources.resource_filename(
        'cernopendata.modules.fixtures', 'data/terms/terms.json')
    with open(filepath, 'r') as f:
        glossary = json.load(f)
    return jsonify(glossary)


@blueprint.route('/collection/<string:collection>')
@blueprint.route('/<any("getting-started","vm","news",'
                 '"datasets","documentation","software"):page>')
@blueprint.route('/<any("getting-started","vm"):page>'
                 '/<any("cms","lhcb","opera","alice","atlas"):experiment>')
def faceted_search(page=None, experiment=None, collection=None):
    """Faceted search view.

    To add a new page:
        add url to blueprint.route
        add mapping, which (filter,val,search_endpoint)
            should be used to filter records

    """
    facets = [x for x in locals().values() if x]
    filters = {}

    filter_map = {
        'documentation': ('type', 'Documentation'),
        'software': ('type', 'Software'),
        'datasets': ('type', 'Dataset'),
        'getting-started': ('tags', 'Getting Started'),
        'news': ('type', 'News'),
        'vm': ('tags', 'VM'),
        'cms': ('experiment', 'CMS'),
        'alice': ('experiment', 'ALICE'),
        'atlas': ('experiment', 'ATLAS'),
        'lhcb': ('experiment', 'LHCb'),
        'opera': ('experiment', 'OPERA'),
        'data-policies': ('collections', 'Data-Policies'),
        'alice-derived-datasets': ('collections',
                                   'ALICE-Derived-Datasets'),
        'alice-reconstructed-data': ('collections',
                                     'ALICE-Reconstructed-Data'),
        'alice-learning-resources': ('collections',
                                     'ALICE-Learning-Resources'),
        'alice-tools': ('collections', 'ALICE-Tools'),
        'atlas-derived-datasets': ('collections',
                                   'ATLAS-Derived-Datasets'),
        'atlas-higgs-challenge-2014': ('collections',
                                       'ATLAS-Higgs-Challenge-2014'),
        'atlas-simulated-datasets': ('collections',
                                     'ATLAS-Simulated-Datasets'),
        'atlas-learning-resources': ('collections',
                                     'ATLAS-Learning-Resources'),
        'atlas-tools': ('collections', 'ATLAS-Tools'),
        'author-lists': ('collections', 'Author-Lists'),

cernopendata/templates/cernopendata_theme/breadcrumbs.html
{%- if breadcrumbs|length > 1 %}
  <ol class="breadcrumb custom-breadcrumb">
    {%- for breadcrumb in breadcrumbs %}
    {%- if loop.last %}
    <li class="breadcrumb-item active">
      {{ breadcrumb.text|safe }}
    </li>
    {%- else %}
    <li class="breadcrumb-item">
      <a href="{{ breadcrumb.url }}">
        {{ breadcrumb.text|safe }}
      </a>
    </li>
    {%- endif %}
    {%- endfor %}
  </ol>
{%- endif %}

cernopendata/templates/cernopendata_theme/footer.html
<section class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4">
        <ul class="list-inline" id="logos">
          <li class="list-inline-item">
            <a href="http://alice.cern.ch"><img src="{{ url_for('static', filename='img/alice.gif') }}" alt=""
                                                width="55" height="55"></a>
          </li>
          <li class="list-inline-item">
            <a href="http://atlas.ch"><img src="{{ url_for('static', filename='img/atlas.gif') }}" alt="" width="55"
                                           height="55"></a>
          </li>
          <li class="list-inline-item">
            <a href="https://cms.cern"><img src="{{ url_for('static', filename='img/cms.gif') }}" alt="" width="55"
                                            height="55"></a></li>
          <li class="list-inline-item">
            <a href="http://lhcb.cern.ch"><img src="{{ url_for('static', filename='img/lhcb.gif') }}" alt="" width="55"
                                               height="55"></a>
          </li>
          <li class="list-inline-item">
            <a href="http://operaweb.lngs.infn.it"><img src="{{ url_for('static', filename='img/opera.gif') }} "
                                                        width="55"
                                                        height="55"
                                                        alt=""></a>
          </li>
        </ul>
      </div>
      <div class="col-md-5">
        {% set year = None %}
        <ul class="list-inline" id="copyright">
          <li class="list-inline-item">© CERN, 2014–{{year|get_year}}  &middot;</li>
          <li class="list-inline-item"><a href="/terms-of-use">Terms of Use</a>  &middot;</li>
          <li class="list-inline-item"><a href="/privacy-policy">Privacy Policy</a>  &middot;</li>
          <li class="list-inline-item"><a href="mailto:opendata-support@cern.ch">Contact</a></li>
        </ul>
      </div>

      <div class="col-md-3">
        <ul class="list-inline">
          <li class="list-inline-item" style="float: right;">
            <a href="http://www.cern.ch">
              <img src="{{url_for('static', filename='assets/img/cern.svg')}}" width="80px"/>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

cernopendata/templates/cernopendata_theme/header.html
{%- extends "invenio_theme/header.html" %}
{%- block navbar %}
<nav class="navbar navbar-expand-lg navbar-custom">
  <a class="navbar-brand" href="{{url_for('cernopendata_pages.index')}}"><img
    src="{{url_for('static', filename='assets/img/logo_blue.png')}}" width="115" alt=""></a>

  {% block search_bar %}
  <div class="searchbar">
      <form {% if request.endpoint=='cernopendata_pages.index' %} id="main-search" {% endif %}
      class="form-inline my-2 my-lg-0" action="{{config.THEME_SEARCH_ENDPOINT}}">
      <div class="input-group w-100">
           <input class="form-control" type="text" placeholder="Search" name="q" aria-label="Search"
                  value="{{ request.args.get('q','')}}">
           <span class="input-group-btn">
             <button class="btn search-btn" type="submit"><span class="oi" data-glyph="magnifying-glass"></span></button>
           </span>
      </div>
      </form>
  </div>
  {% endblock search_bar %}

  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
        About <b class="caret"></b>
      </a>
      <ul class="dropdown-menu dropdown-menu-right about-menu">
        <li><a class="dropdown-item" href="/docs/about">This Portal</a></li>
        <li><a class="dropdown-item" href="/docs/about-alice">ALICE Open Data</a></li>
        <li><a class="dropdown-item" href="/docs/about-atlas">ATLAS Open Data</a></li>
        <li><a class="dropdown-item" href="/docs/about-cms">CMS Open Data</a></li>
        <li><a class="dropdown-item" href="/docs/about-lhcb">LHCb Open Data</a></li>
        <li><a class="dropdown-item" href="/docs/about-opera">OPERA Open Data</a></li>
        <li><a class="dropdown-item" href="/search?type=Glossary&sort=title">Glossary</a></li>
        <li><a class="dropdown-item" href="/docs/privacy-policy">Privacy</a></li>
      </ul>
    </li>
  </ul>
</nav>

{%- endblock navbar %}

{%- block breadcrumbs %}
{%- include "cernopendata_theme/breadcrumbs.html" %}
{%- endblock breadcrumbs %}

cernopendata/templates/cernopendata_theme/header_index.html
{%- extends "cernopendata_theme/header.html" %}

{% block search_bar %}{% endblock search_bar %}

cernopendata/templates/cernopendata_theme/page.html
{% extends 'invenio_theme/page.html' %}

{% block css %}
    {%- assets "cernopendata_theme_css" %}<link href="{{ ASSET_URL }}" rel="stylesheet"> {%- endassets %}
    {%- assets "cernopendata_glossary_css" %} <link href="{{ ASSET_URL }}" rel="stylesheet"> {%- endassets %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{%- endblock css %}


{%- block body_inner %}
  <!--Wrapper for page content to push down footer-->
  <div id="footer_wrap">
    <!-- Begin page content -->
    {%- block page_header %}
    {% include 'cernopendata_theme/header.html' %}
    {%- endblock page_header %}

      {%- block page_body %}
      {%- block page_body_top %}{%- endblock page_body_top %}

      {%- endblock page_body %}

    <!-- End page content -->
    <div id="footer_push"></div> <!-- Make room for footer -->

  </div>

  {%- block page_footer %}
  {% include "cernopendata_theme/footer.html" %}
  {%- endblock page_footer %}

{%- endblock body_inner %}

{%- block javascript %}
  {% assets "cernopendata_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
  {% assets "cernopendata_glossary_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
  {% assets "cernopendata_search_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}

  {%- block javascript_glossary %}

    <script>
        $(document).ready(function () {
          $('body').glossary('/glossary/json');

          var reference = document.querySelector('.my-button');
          $('[data-toggle="popover"]').popover('show')
        });
    </script>
  {% endblock %}

  {%- block mathjax_support %}
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js"],
        jax: ["input/TeX", "output/HTML-CSS"],
        tex2jax: {
          inlineMath: [ ['$','$'], ["\\(","\\)"] ],
          displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
          processEscapes: true
        },
        "HTML-CSS": { availableFonts: ["TeX"] }
      });
    </script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML"></script>
  {% endblock %}

{% endblock %}